version: "3"
services:
  playground-mysql:
    container_name: playground-mysql
    image: mysql:8.0.32
    platform: linux/amd64
    networks:
      - playground-network
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=playground
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=password
      - TZ=Asia/Seoul
    command: --character-set-server=UTF8MB4 --collation-server=utf8mb4_unicode_ci --default-authentication-plugin=mysql_native_password --lower_case_table_names=1 --sql-mode="STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION"
    volumes:
      - ./volumes/mysql:/var/lib/mysqld
  playground-redis:
    container_name: playground-redis
    image: redis:latest
    platform: linux/x86_64 # linux/arm64, linux/x86_64, linux/amd64
    restart: always
    networks:
      - playground-network
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - "6379:6379"
    volumes:
      - ./volumes/redis:/data
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: 500M
    user: "1004757"
networks:
  playground-network:
